[env:simple-commander]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Point to the shared libraries folder
lib_extra_dirs = ../libraries

; Dependencies
lib_deps = 
    HeroPropsProtocol
    ; Add other libs if needed (e.g. for Joystick or Display)

build_flags = 
    -D CORE_DEBUG_LEVEL=3
