; =========================================================================
; 🤖 L0-0N — New Baseline (Bakken Spring Break 2026)
; =========================================================================
[env:l0-0n]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    https://github.com/SeanMcArdle/HeroPropsProtocol.git
    madhephaestus/ESP32Servo @ ^1.1.0
    adafruit/Adafruit NeoPixel @ ^1.12.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D BOT_ID=1

[env:l0-0n-ota]
extends = env:l0-0n
upload_protocol = espota
upload_port = 192.168.4.1
upload_flags =
    --auth=heroprops

