[env:jl-bn]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; Point to the shared libraries folder
lib_extra_dirs = ../libraries

; Dependencies
lib_deps = 
    HeroPropsProtocol
    madhephaestus/ESP32Servo @ ^1.1.0
    fastled/FastLED @ ^3.6.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0

; Build flags
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUHAL_LOG_COLORS=1
