[platformio]
default_envs = captain

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = ../libraries
lib_deps = 
    HeroPropsProtocol
    madhephaestus/ESP32Servo @ ^1.1.0
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    adafruit/Adafruit NeoPixel @ ^1.12.0
build_flags = 
    -D CORE_DEBUG_LEVEL=3

[env:captain]
description = The Main Brain (Torso)
board = esp32dev
build_flags = 
    ${env.build_flags}
    -D ROLE_CAPTAIN

[env:bard]
description = The Audio Controller (Torso)
board = esp32dev
lib_deps =
    ${env.lib_deps}
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
build_flags = 
    ${env.build_flags}
    -D ROLE_BARD
    -D I2S_SPEAKER_SERIAL_CLOCK=14
    -D I2S_SPEAKER_LEFT_RIGHT_CLOCK=12
    -D I2S_SPEAKER_SERIAL_DATA=27
    -D I2S_MIC_SERIAL_CLOCK=18
    -D I2S_MIC_LEFT_RIGHT_CLOCK=19
    -D I2S_MIC_SERIAL_DATA=21

[env:lookout]
description = The Dome Controller (Dome)
board = esp32dev
build_flags = 
    ${env.build_flags}
    -D ROLE_LOOKOUT

[env:eye]
description = The Chopper Eye (Dome)
board = esp32cam
build_flags = 
    ${env.build_flags}
    -D ROLE_EYE
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue